"""initial schema (pgvector extension + all tables)

Revision ID: 0001_init
Revises:
Create Date: 2026-06-01

We build the schema from the SQLModel metadata to guarantee it matches the
models exactly. Subsequent changes should use autogenerated revisions:
    alembic revision --autogenerate -m "describe change"
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlmodel import SQLModel

import app.models  # noqa: F401  (registers tables on the metadata)

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    SQLModel.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind)
